export const NATIONALITIES = [
  // 🇪🇺 Europe (main countries)
  "Austria",
  "Belgium",
  "Croatia",
  "Czech Republic",
  "Denmark",
  "Estonia",
  "Finland",
  "France",
  "Germany",
  "Greece",
  "Hungary",
  "Iceland",
  "Ireland",
  "Italy",
  "Latvia",
  "Lithuania",
  "Luxembourg",
  "Malta",
  "Netherlands",
  "Norway",
  "Poland",
  "Portugal",
  "Romania",
  "Serbia",
  "Slovakia",
  "Slovenia",
  "Spain",
  "Sweden",
  "Switzerland",
  "United Kingdom",
  "Ukraine",
  "Russia",

  // 🇪🇺 Smaller/Other European countries
  "Albania",
  "Andorra",
  "Bosnia and Herzegovina",
  "Bulgaria",
  "Cyprus",
  "Georgia",
  "Kosovo",
  "Moldova",
  "Montenegro",
  "North Macedonia",

  // 🌎 South America
  "Argentina",
  "Bolivia",
  "Brazil",
  "Chile",
  "Colombia",
  "Ecuador",
  "Paraguay",
  "Peru",
  "Uruguay",
  "Venezuela",

  // 🇲🇽 Central / North America
  "Mexico",
  "United States",
  "Canada",

  // 🌏 Asia (main countries)
  "China",
  "India",
  "Japan",
  "South Korea",
  "Thailand",
  "Philippines",
  "Vietnam",
  "Indonesia",
  "Malaysia",
  "Singapore",
  "Israel",
  "Turkey",
  "United Arab Emirates",
  "Kazakhstan",

  // 🌏 Oceania
  "Australia",
  "New Zealand",
];
